### ISSUE TITLE
【建议】 关于通知类的建议

### ISSUE THREAD

**Issue by nankaine** [KNaiFen/Live_Proxy_Api#1]
你好，感谢分享这个工具。
不知道能否增加一个webhook的形式的通知呢

以及如果是邮件的话，能否增加一个测试发邮件是否正常的功能。 谢谢

**Comment by jkfujr** [comment]
有空写写吧...目前在解决数据请求的问题

**Comment by jkfujr** [comment]
https://github.com/KNaiFen/Live_Proxy_Api/commit/f2e0f06f20d688e875a940305d9e392226a6fd44
邮件测试加上了, 调用地址是 `/api/smtp/test` 需要APIKEY
可以运行 `Status.py` 进行测试，或者在webui上点击测试

至于 `webhook` ，正在测试

**Comment by jkfujr** [comment]
https://github.com/KNaiFen/Live_Proxy_Api/commit/a4fe2da416e1570b758c6988663acc0fb6d7f7af

加上了，邮件能通知到的webhook也能通知到了，添加webhook服务器的话，看示例配置
